services:
  zincsearch:
    image: public.ecr.aws/zinclabs/zincsearch:latest
    container_name: zincsearch
    environment:
      - ZINC_DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123
    volumes:
      - ./data:/data
    ports:
      - "4080:4080"
    restart: unless-stopped

  api:
    build: ./api
    container_name: indexer-api
    ports:
      - "8080:8080"
    environment:
      - ZINCSEARCH_URL=http://localhost:4080
      - ZINCSEARCH_USER=admin
      - ZINCSEARCH_PASSWORD=Complexpass#123
    depends_on:
      - zincsearch
    restart: unless-stopped

  web-client:
    build: ./web-client
    container_name: indexer-web-client
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - api
    restart: unless-stopped
